import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { getModelToken } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import * as bcrypt from 'bcrypt';
import { User, UserDocument } from './users/schemas/user.schema';
import { Product, ProductDocument } from './products/schemas/product.schema';
import { Category, CategoryDocument } from './categories/schemas/category.schema';
import { Brand, BrandDocument } from './brands/schemas/brand.schema';
import { Coupon, CouponDocument } from './coupons/schemas/coupon.schema';
import { Banner, BannerDocument } from './banners/schemas/banner.schema';
import { Review, ReviewDocument } from './reviews/schemas/review.schema';
import { StoreSettings, StoreSettingsDocument } from './settings/schemas/settings.schema';
import { Role, CouponType } from './common/enums';

// Seed Datasets matching frontend mock data with AT LEAST 3 products per subcategory
const seedProducts = [
  // ==================== BOYS CATEGORY ====================
  // 1. Kurta Pyjama (4 products)
  {
    id: 'th-b101',
    name: 'Sky Blue Silk Kurta Pyjama Set',
    slug: 'sky-blue-silk-kurta-pyjama-set',
    category: 'Boys',
    subcategory: 'Kurta Pyjama',
    collectionName: 'Festive',
    brand: 'Tohay Heritage',
    ageRange: '0-8',
    sizes: ['0-2Y', '2-4Y', '4-6Y', '6-8Y'],
    colors: [{ name: 'Sky Blue', hex: '#38BDF8' }],
    price: 2299,
    mrp: 2999,
    rating: 4.8,
    reviewsCount: 18,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: false,
    stock: 20,
    images: ['https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Sleek sky blue jacquard kurta with elasticated pyjamas. Soft silk blend for all day comfort.',
    fabric: 'Jacquard Cotton Silk',
    care: 'Hand Wash',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-b102',
    name: 'Mint Green Cotton Silk Kurta Set',
    slug: 'mint-green-cotton-silk-kurta-set',
    category: 'Boys',
    subcategory: 'Kurta Pyjama',
    collectionName: 'Festive',
    brand: 'Tohay Heritage',
    ageRange: '0-8',
    sizes: ['0-2Y', '2-4Y', '4-6Y'],
    colors: [{ name: 'Mint Green', hex: '#6EE7B7' }],
    price: 1999,
    mrp: 2699,
    rating: 4.7,
    reviewsCount: 14,
    isNew: true,
    isTrending: false,
    isBestseller: true,
    isSale: true,
    stock: 15,
    images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Gentle mint green cotton silk kurta pyjama set with subtle woven motifs.',
    fabric: 'Cotton Silk Blend',
    care: 'Hand Wash',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-b103',
    name: 'Royal Navy Blue Silk Kurta Set',
    slug: 'royal-navy-blue-silk-kurta-set',
    category: 'Boys',
    subcategory: 'Kurta Pyjama',
    collectionName: 'Wedding',
    brand: 'Tohay Heritage',
    ageRange: '9-12',
    sizes: ['6-8Y', '9-12Y', '13-16Y'],
    colors: [{ name: 'Navy', hex: '#1E3A8A' }],
    price: 2499,
    mrp: 3299,
    rating: 4.9,
    reviewsCount: 23,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: false,
    stock: 18,
    images: ['https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Deep navy blue silk kurta set with shiny thread embroidery.',
    fabric: 'Silk Dupion',
    care: 'Dry Clean Only',
    occasion: 'Wedding',
    isActive: true
  },
  {
    id: 'th-b104',
    name: 'Maroon Velvet Silk Kurta Pyjama',
    slug: 'maroon-velvet-silk-kurta-pyjama',
    category: 'Boys',
    subcategory: 'Kurta Pyjama',
    collectionName: 'Festive',
    brand: 'Tohay Heritage',
    ageRange: '13-16',
    sizes: ['9-12Y', '13-16Y'],
    colors: [{ name: 'Maroon', hex: '#800000' }],
    price: 2799,
    mrp: 3599,
    rating: 4.8,
    reviewsCount: 9,
    isNew: true,
    isTrending: true,
    isBestseller: false,
    isSale: true,
    stock: 14,
    images: ['https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Rich maroon festive kurta with golden button detailing.',
    fabric: 'Soft Velvet Silk',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },

  // 2. Nehru Jacket Sets (3 products)
  {
    id: 'th-b201',
    name: 'Sky Blue Brocade Nehru Jacket Set',
    slug: 'sky-blue-brocade-nehru-jacket-set',
    category: 'Boys',
    subcategory: 'Nehru Jacket Sets',
    collectionName: 'Festive',
    brand: 'Little Royal',
    ageRange: '0-8',
    sizes: ['4-6Y', '6-8Y'],
    colors: [{ name: 'Sky Blue', hex: '#38BDF8' }],
    price: 2799,
    mrp: 3599,
    rating: 4.7,
    reviewsCount: 15,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: true,
    stock: 11,
    images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Smart sky blue Nehru jacket over white kurta pyjama.',
    fabric: 'Silk Brocade',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-b202',
    name: 'Golden Zari Woven Nehru Jacket Set',
    slug: 'golden-zari-woven-nehru-jacket-set',
    category: 'Boys',
    subcategory: 'Nehru Jacket Sets',
    collectionName: 'Wedding',
    brand: 'Tohay Heritage',
    ageRange: '9-12',
    sizes: ['6-8Y', '9-12Y'],
    colors: [{ name: 'Yellow', hex: '#EAB308' }],
    price: 2999,
    mrp: 3899,
    rating: 4.9,
    reviewsCount: 20,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: false,
    stock: 9,
    images: ['https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Regal golden zari jacquard jacket paired with crisp cream kurta.',
    fabric: 'Jacquard Silk',
    care: 'Dry Clean Only',
    occasion: 'Wedding',
    isActive: true
  },
  {
    id: 'th-b203',
    name: 'Peach Floral Jacquard Nehru Jacket Set',
    slug: 'peach-floral-jacquard-nehru-jacket-set',
    category: 'Boys',
    subcategory: 'Nehru Jacket Sets',
    collectionName: 'Festive',
    brand: 'Little Royal',
    ageRange: '13-16',
    sizes: ['9-12Y', '13-16Y'],
    colors: [{ name: 'Peach', hex: '#FFAB91' }],
    price: 3199,
    mrp: 3999,
    rating: 4.8,
    reviewsCount: 11,
    isNew: true,
    isTrending: false,
    isBestseller: true,
    isSale: true,
    stock: 14,
    images: ['https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Elegant peach floral printed Nehru jacket set with pyjamas.',
    fabric: 'Raw Silk',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },

  // 3. Sherwani Sets (3 products)
  {
    id: 'th-b301',
    name: 'Cream Royal Embroidered Sherwani Set',
    slug: 'cream-royal-embroidered-sherwani-set',
    category: 'Boys',
    subcategory: 'Sherwani Sets',
    collectionName: 'Wedding',
    brand: 'Tohay Heritage',
    ageRange: '0-8',
    sizes: ['2-4Y', '4-6Y', '6-8Y'],
    colors: [{ name: 'Cream', hex: '#FFFDD0' }],
    price: 3899,
    mrp: 4999,
    rating: 5.0,
    reviewsCount: 22,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: false,
    stock: 8,
    images: ['https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Regal cream embroidered sherwani set with mandarin collar and churidar.',
    fabric: 'Jacquard Silk',
    care: 'Dry Clean Only',
    occasion: 'Wedding',
    isActive: true
  },
  {
    id: 'th-b302',
    name: 'Crimson Red Velvet Royal Sherwani Set',
    slug: 'crimson-red-velvet-royal-sherwani-set',
    category: 'Boys',
    subcategory: 'Sherwani Sets',
    collectionName: 'Wedding',
    brand: 'Tohay Heritage',
    ageRange: '9-12',
    sizes: ['6-8Y', '9-12Y'],
    colors: [{ name: 'Maroon', hex: '#880E4F' }],
    price: 4299,
    mrp: 5499,
    rating: 4.9,
    reviewsCount: 17,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: true,
    stock: 10,
    images: ['https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Majestic crimson velvet sherwani with golden zari embroidery.',
    fabric: 'Royal Velvet & Silk',
    care: 'Dry Clean Only',
    occasion: 'Wedding',
    isActive: true
  },
  {
    id: 'th-b303',
    name: 'Heritage Gold Silk Sherwani Set',
    slug: 'heritage-gold-silk-sherwani-set',
    category: 'Boys',
    subcategory: 'Sherwani Sets',
    collectionName: 'Wedding',
    brand: 'Tohay Heritage',
    ageRange: '13-16',
    sizes: ['9-12Y', '13-16Y'],
    colors: [{ name: 'Yellow', hex: '#FDE047' }],
    price: 4499,
    mrp: 5999,
    rating: 4.8,
    reviewsCount: 13,
    isNew: true,
    isTrending: false,
    isBestseller: true,
    isSale: false,
    stock: 6,
    images: ['https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Opulent gold silk sherwani set with brooch and matching churidar.',
    fabric: 'Art Brocade Silk',
    care: 'Dry Clean Only',
    occasion: 'Wedding',
    isActive: true
  },

  // 4. Indo Western Sets (3 products)
  {
    id: 'th-b401',
    name: 'Beige Asymmetric Overlap Indo Western Set',
    slug: 'beige-asymmetric-overlap-indo-western-set',
    category: 'Boys',
    subcategory: 'Indo Western Sets',
    collectionName: 'Party',
    brand: 'Little Royal',
    ageRange: '0-8',
    sizes: ['2-4Y', '4-6Y', '6-8Y'],
    colors: [{ name: 'Peach', hex: '#FFAB91' }],
    price: 2699,
    mrp: 3499,
    rating: 4.7,
    reviewsCount: 12,
    isNew: true,
    isTrending: false,
    isBestseller: true,
    isSale: true,
    stock: 10,
    images: ['https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Dapper beige overlap jacket styled Indo Western set for little gents.',
    fabric: 'Cotton Linen Blend',
    care: 'Dry Clean Only',
    occasion: 'Party',
    isActive: true
  },
  {
    id: 'th-b402',
    name: 'Black Embroidered Designer Indo Western Set',
    slug: 'black-embroidered-designer-indo-western-set',
    category: 'Boys',
    subcategory: 'Indo Western Sets',
    collectionName: 'Party',
    brand: 'Little Royal',
    ageRange: '13-16',
    sizes: ['9-12Y', '13-16Y'],
    colors: [{ name: 'Teal', hex: '#0F766E' }],
    price: 2999,
    mrp: 3999,
    rating: 4.9,
    reviewsCount: 7,
    isNew: true,
    isTrending: true,
    isBestseller: false,
    isSale: false,
    stock: 16,
    images: ['https://images.unsplash.com/photo-1476493279419-b785d41e2618?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Tailored black Indo Western ensemble with subtle self embroidery.',
    fabric: 'Viscose Blend',
    care: 'Dry Clean Only',
    occasion: 'Party',
    isActive: true
  },
  {
    id: 'th-b403',
    name: 'Pastel Lavender Indo Western Suit',
    slug: 'pastel-lavender-indo-western-suit',
    category: 'Boys',
    subcategory: 'Indo Western Sets',
    collectionName: 'Party',
    brand: 'Tohay Heritage',
    ageRange: '9-12',
    sizes: ['6-8Y', '9-12Y'],
    colors: [{ name: 'Lavender', hex: '#CE93D8' }],
    price: 2899,
    mrp: 3699,
    rating: 4.8,
    reviewsCount: 16,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: true,
    stock: 12,
    images: ['https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Trendy pastel lavender Indo Western jacket set with fitted pants.',
    fabric: 'Terry Rayon Blend',
    care: 'Dry Clean Only',
    occasion: 'Party',
    isActive: true
  },

  // 5. Dhoti Kurta Sets (3 products)
  {
    id: 'th-b501',
    name: 'Sunshine Yellow Gota Work Dhoti Kurta Set',
    slug: 'sunshine-yellow-gota-work-dhoti-kurta-set',
    category: 'Boys',
    subcategory: 'Dhoti Kurta Sets',
    collectionName: 'Festive',
    brand: 'Festive Blooms',
    ageRange: '0-8',
    sizes: ['0-2Y', '2-4Y', '4-6Y'],
    colors: [{ name: 'Yellow', hex: '#FDE047' }],
    price: 2199,
    mrp: 2899,
    rating: 4.9,
    reviewsCount: 19,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: true,
    stock: 14,
    images: ['https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Vibrant yellow silk short kurta paired with pre-stitched readymade dhoti.',
    fabric: 'Art Silk',
    care: 'Hand Wash Soft',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-b502',
    name: 'Royal Blue Silk Angrakha Dhoti Kurta Set',
    slug: 'royal-blue-silk-angrakha-dhoti-kurta-set',
    category: 'Boys',
    subcategory: 'Dhoti Kurta Sets',
    collectionName: 'Festive',
    brand: 'Tohay Heritage',
    ageRange: '9-12',
    sizes: ['6-8Y', '9-12Y'],
    colors: [{ name: 'Sky Blue', hex: '#38BDF8' }],
    price: 2499,
    mrp: 3299,
    rating: 4.8,
    reviewsCount: 14,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: false,
    stock: 11,
    images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Angrakha style royal blue silk kurta with gold border dhoti.',
    fabric: 'Chanderi Silk',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-b503',
    name: 'Emerald Green Printed Dhoti Kurta Set',
    slug: 'emerald-green-printed-dhoti-kurta-set',
    category: 'Boys',
    subcategory: 'Dhoti Kurta Sets',
    collectionName: 'Festive',
    brand: 'Festive Blooms',
    ageRange: '13-16',
    sizes: ['9-12Y', '13-16Y'],
    colors: [{ name: 'Mint Green', hex: '#A5D6A7' }],
    price: 2599,
    mrp: 3399,
    rating: 4.7,
    reviewsCount: 10,
    isNew: true,
    isTrending: false,
    isBestseller: true,
    isSale: true,
    stock: 9,
    images: ['https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Traditional emerald green printed kurta set with contrasting dhoti.',
    fabric: 'Pure Cotton Silk',
    care: 'Hand Wash',
    occasion: 'Festive',
    isActive: true
  },

  // ==================== GIRLS CATEGORY ====================
  // 1. Lehenga Choli (4 products)
  {
    id: 'th-g101',
    name: 'Floral Orange Lehenga Choli With Dupatta',
    slug: 'floral-orange-lehenga-choli-with-dupatta',
    category: 'Girls',
    subcategory: 'Lehenga Choli',
    collectionName: 'Festive',
    brand: 'Tohay Heritage',
    ageRange: '0-8',
    sizes: ['0-2Y', '2-4Y', '4-6Y', '6-8Y'],
    colors: [{ name: 'Pink', hex: '#FF80AB' }],
    price: 2352,
    mrp: 3299,
    rating: 4.8,
    reviewsCount: 23,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: true,
    stock: 14,
    images: ['https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Vibrant orange floral printed lehenga choli set with soft festive borders.',
    fabric: 'Pure Silk Blend & Chiffon Dupatta',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-g102',
    name: 'Lavender Net Embroidered Lehenga Choli',
    slug: 'lavender-net-embroidered-lehenga-choli',
    category: 'Girls',
    subcategory: 'Lehenga Choli',
    collectionName: 'Wedding',
    brand: 'Tohay Heritage',
    ageRange: '9-12',
    sizes: ['6-8Y', '9-12Y', '13-16Y'],
    colors: [{ name: 'Lavender', hex: '#CE93D8' }],
    price: 2599,
    mrp: 3599,
    rating: 4.9,
    reviewsCount: 26,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: true,
    stock: 11,
    images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Royal lavender embroidered net lehenga with handcrafted mirror work.',
    fabric: 'Embroidered Net & Satin Lining',
    care: 'Dry Clean Only',
    occasion: 'Wedding',
    isActive: true
  },
  {
    id: 'th-g103',
    name: 'Mint Green Chanderi Silk Lehenga Set',
    slug: 'mint-green-chanderi-silk-lehenga-set',
    category: 'Girls',
    subcategory: 'Lehenga Choli',
    collectionName: 'Festive',
    brand: 'Festive Blooms',
    ageRange: '0-8',
    sizes: ['2-4Y', '4-6Y', '6-8Y'],
    colors: [{ name: 'Mint Green', hex: '#A5D6A7' }],
    price: 2499,
    mrp: 3299,
    rating: 4.8,
    reviewsCount: 22,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: false,
    stock: 12,
    images: ['https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Fresh mint green festive lehenga set with golden gota patti borders.',
    fabric: 'Chanderi Silk',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-g104',
    name: 'Crimson Red Velvet Festive Lehenga Choli',
    slug: 'crimson-red-velvet-festive-lehenga-choli',
    category: 'Girls',
    subcategory: 'Lehenga Choli',
    collectionName: 'Wedding',
    brand: 'Tohay Heritage',
    ageRange: '13-16',
    sizes: ['9-12Y', '13-16Y'],
    colors: [{ name: 'Maroon', hex: '#880E4F' }],
    price: 3499,
    mrp: 4499,
    rating: 5.0,
    reviewsCount: 15,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: true,
    stock: 8,
    images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Grand crimson red velvet lehenga choli with zardozi handwork.',
    fabric: 'Royal Velvet Silk',
    care: 'Dry Clean Only',
    occasion: 'Wedding',
    isActive: true
  },

  // 2. Party Gowns (3 products)
  {
    id: 'th-g201',
    name: 'Pastel Pink Layered Tulle Party Gown',
    slug: 'pastel-pink-layered-tulle-party-gown',
    category: 'Girls',
    subcategory: 'Party Gowns',
    collectionName: 'Party',
    brand: 'Little Royal',
    ageRange: '0-8',
    sizes: ['2-4Y', '4-6Y', '6-8Y'],
    colors: [{ name: 'Pink', hex: '#FF80AB' }],
    price: 2199,
    mrp: 2999,
    rating: 4.7,
    reviewsCount: 18,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: true,
    stock: 9,
    images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Dreamy layered tulle gown in pastel pink with subtle zari embroidery accents.',
    fabric: 'Soft Net & Cotton Lining',
    care: 'Dry Clean Only',
    occasion: 'Birthday',
    isActive: true
  },
  {
    id: 'th-g202',
    name: 'Sparkling Sky Blue Sequins Party Gown',
    slug: 'sparkling-sky-blue-sequins-party-gown',
    category: 'Girls',
    subcategory: 'Party Gowns',
    collectionName: 'Party',
    brand: 'Little Royal',
    ageRange: '9-12',
    sizes: ['6-8Y', '9-12Y'],
    colors: [{ name: 'Sky Blue', hex: '#38BDF8' }],
    price: 2699,
    mrp: 3499,
    rating: 4.9,
    reviewsCount: 21,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: false,
    stock: 13,
    images: ['https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Fairytale sky blue sequin embroidered party gown with flare.',
    fabric: 'Sequined Satin Net',
    care: 'Dry Clean Only',
    occasion: 'Party',
    isActive: true
  },
  {
    id: 'th-g203',
    name: 'Royal Peach Embroidered Festive Party Gown',
    slug: 'royal-peach-embroidered-festive-party-gown',
    category: 'Girls',
    subcategory: 'Party Gowns',
    collectionName: 'Party',
    brand: 'Little Royal',
    ageRange: '13-16',
    sizes: ['9-12Y', '13-16Y'],
    colors: [{ name: 'Peach', hex: '#FFAB91' }],
    price: 2899,
    mrp: 3699,
    rating: 4.8,
    reviewsCount: 16,
    isNew: true,
    isTrending: false,
    isBestseller: true,
    isSale: true,
    stock: 10,
    images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Elegant peach floor-length gown with stone embroidery.',
    fabric: 'Georgette & Satin',
    care: 'Dry Clean Only',
    occasion: 'Party',
    isActive: true
  },

  // 3. Sharara Sets (3 products)
  {
    id: 'th-g301',
    name: 'Sunshine Yellow Peplum Sharara Set',
    slug: 'sunshine-yellow-peplum-sharara-set',
    category: 'Girls',
    subcategory: 'Sharara Sets',
    collectionName: 'Festive',
    brand: 'Festive Blooms',
    ageRange: '0-8',
    sizes: ['2-4Y', '4-6Y', '6-8Y'],
    colors: [{ name: 'Yellow', hex: '#FDE047' }],
    price: 2199,
    mrp: 2799,
    rating: 4.9,
    reviewsCount: 19,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: true,
    stock: 15,
    images: ['https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Sunshine yellow peplum short kurti paired with flared sharara pants.',
    fabric: 'Georgette',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-g302',
    name: 'Magenta Pink Mirror Work Sharara Set',
    slug: 'magenta-pink-mirror-work-sharara-set',
    category: 'Girls',
    subcategory: 'Sharara Sets',
    collectionName: 'Festive',
    brand: 'Festive Blooms',
    ageRange: '9-12',
    sizes: ['6-8Y', '9-12Y'],
    colors: [{ name: 'Pink', hex: '#FF80AB' }],
    price: 2499,
    mrp: 3199,
    rating: 4.8,
    reviewsCount: 14,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: false,
    stock: 11,
    images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Vibrant magenta pink short kurti with mirror work sharara pants.',
    fabric: 'Cotton Silk',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-g303',
    name: 'Turquoise Green Embroidered Sharara Set',
    slug: 'turquoise-green-embroidered-sharara-set',
    category: 'Girls',
    subcategory: 'Sharara Sets',
    collectionName: 'Festive',
    brand: 'Tohay Heritage',
    ageRange: '13-16',
    sizes: ['9-12Y', '13-16Y'],
    colors: [{ name: 'Teal', hex: '#0F766E' }],
    price: 2699,
    mrp: 3499,
    rating: 4.7,
    reviewsCount: 12,
    isNew: true,
    isTrending: false,
    isBestseller: true,
    isSale: true,
    stock: 8,
    images: ['https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Rich turquoise green embroidered kurti with pleated sharara.',
    fabric: 'Chiffon Georgette',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },

  // 4. Anarkali Sets (3 products)
  {
    id: 'th-g401',
    name: 'Pastel Green Floral Print Anarkali Set',
    slug: 'pastel-green-floral-print-anarkali-set',
    category: 'Girls',
    subcategory: 'Anarkali Sets',
    collectionName: 'Festive',
    brand: 'Festive Blooms',
    ageRange: '0-8',
    sizes: ['2-4Y', '4-6Y', '6-8Y'],
    colors: [{ name: 'Mint Green', hex: '#A5D6A7' }],
    price: 2399,
    mrp: 2999,
    rating: 4.8,
    reviewsCount: 17,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: true,
    stock: 14,
    images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Flowy mint green floral printed Anarkali set with churidar.',
    fabric: 'Pure Mulberry Silk Blend',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-g402',
    name: 'Royal Navy Blue Gota Patti Anarkali Suit',
    slug: 'royal-navy-blue-gota-patti-anarkali-suit',
    category: 'Girls',
    subcategory: 'Anarkali Sets',
    collectionName: 'Festive',
    brand: 'Tohay Heritage',
    ageRange: '9-12',
    sizes: ['6-8Y', '9-12Y'],
    colors: [{ name: 'Navy', hex: '#1E3A8A' }],
    price: 2799,
    mrp: 3599,
    rating: 4.9,
    reviewsCount: 20,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: false,
    stock: 10,
    images: ['https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Deep navy blue floor-length Anarkali with golden gota borders.',
    fabric: 'Art Silk Dupion',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-g403',
    name: 'Crimson Red Festive Silk Anarkali Set',
    slug: 'crimson-red-festive-silk-anarkali-set',
    category: 'Girls',
    subcategory: 'Anarkali Sets',
    collectionName: 'Wedding',
    brand: 'Tohay Heritage',
    ageRange: '13-16',
    sizes: ['9-12Y', '13-16Y'],
    colors: [{ name: 'Maroon', hex: '#880E4F' }],
    price: 2999,
    mrp: 3899,
    rating: 4.8,
    reviewsCount: 13,
    isNew: true,
    isTrending: false,
    isBestseller: true,
    isSale: true,
    stock: 9,
    images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Traditional red heavy flare Anarkali with dupatta.',
    fabric: 'Silk Georgette',
    care: 'Dry Clean Only',
    occasion: 'Wedding',
    isActive: true
  },

  // 5. Dhoti Kurti Sets (3 products)
  {
    id: 'th-g501',
    name: 'Bright Yellow Silk Dhoti Kurti Set',
    slug: 'bright-yellow-silk-dhoti-kurti-set',
    category: 'Girls',
    subcategory: 'Dhoti Kurti Sets',
    collectionName: 'Festive',
    brand: 'Festive Blooms',
    ageRange: '0-8',
    sizes: ['0-2Y', '2-4Y', '4-6Y'],
    colors: [{ name: 'Yellow', hex: '#FDE047' }],
    price: 2099,
    mrp: 2699,
    rating: 4.8,
    reviewsCount: 15,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: true,
    stock: 12,
    images: ['https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Chic bright yellow short kurti with flared printed dhoti pants.',
    fabric: 'Cotton Silk',
    care: 'Hand Wash',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-g502',
    name: 'Peach Angrakha Dhoti Kurti Set',
    slug: 'peach-angrakha-dhoti-kurti-set',
    category: 'Girls',
    subcategory: 'Dhoti Kurti Sets',
    collectionName: 'Festive',
    brand: 'Little Royal',
    ageRange: '9-12',
    sizes: ['6-8Y', '9-12Y'],
    colors: [{ name: 'Peach', hex: '#FFAB91' }],
    price: 2299,
    mrp: 2999,
    rating: 4.7,
    reviewsCount: 11,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: false,
    stock: 10,
    images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Angrakha style peach short kurti paired with satin dhoti pants.',
    fabric: 'Art Silk',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-g503',
    name: 'Royal Purple Embroidered Dhoti Kurti Set',
    slug: 'royal-purple-embroidered-dhoti-kurti-set',
    category: 'Girls',
    subcategory: 'Dhoti Kurti Sets',
    collectionName: 'Festive',
    brand: 'Tohay Heritage',
    ageRange: '13-16',
    sizes: ['9-12Y', '13-16Y'],
    colors: [{ name: 'Lavender', hex: '#CE93D8' }],
    price: 2499,
    mrp: 3299,
    rating: 4.9,
    reviewsCount: 14,
    isNew: true,
    isTrending: false,
    isBestseller: true,
    isSale: true,
    stock: 8,
    images: ['https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Rich royal purple embroidered kurti with metallic border dhoti.',
    fabric: 'Chanderi Silk',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },

  // ==================== SIBLINGS CATEGORY ====================
  // 1. Brother & Sister Sets (3 products)
  {
    id: 'th-s101',
    name: 'Maroon Gold Brother & Sister Festive Set',
    slug: 'maroon-gold-brother-and-sister-festive-set',
    category: 'Siblings',
    subcategory: 'Brother & Sister Sets',
    collectionName: 'Festive',
    brand: 'Festive Blooms',
    ageRange: '0-8',
    sizes: ['Combo 4Y & 6Y', 'Combo 6Y & 8Y'],
    colors: [{ name: 'Maroon', hex: '#880E4F' }],
    price: 4299,
    mrp: 5999,
    rating: 5.0,
    reviewsCount: 24,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: true,
    stock: 9,
    images: ['https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Coordinated maroon & gold brother-sister ethnic wear combo set.',
    fabric: 'Chanderi Silk & Jacquard',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-s102',
    name: 'Royal Blue Silk Brother & Sister Wedding Combo',
    slug: 'royal-blue-silk-brother-and-sister-wedding-combo',
    category: 'Siblings',
    subcategory: 'Brother & Sister Sets',
    collectionName: 'Wedding',
    brand: 'Tohay Heritage',
    ageRange: '9-12',
    sizes: ['Combo 8Y & 10Y', 'Combo 10Y & 12Y'],
    colors: [{ name: 'Sky Blue', hex: '#38BDF8' }],
    price: 4699,
    mrp: 6299,
    rating: 4.9,
    reviewsCount: 18,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: false,
    stock: 7,
    images: ['https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Royal blue brother kurta set and sister lehenga choli wedding combo.',
    fabric: 'Raw Silk & Net',
    care: 'Dry Clean Only',
    occasion: 'Wedding',
    isActive: true
  },
  {
    id: 'th-s103',
    name: 'Mustard Yellow Gota Patti Brother & Sister Set',
    slug: 'mustard-yellow-gota-patti-brother-and-sister-set',
    category: 'Siblings',
    subcategory: 'Brother & Sister Sets',
    collectionName: 'Festive',
    brand: 'Festive Blooms',
    ageRange: '13-16',
    sizes: ['Combo 12Y & 14Y', 'Combo 14Y & 16Y'],
    colors: [{ name: 'Yellow', hex: '#FDE047' }],
    price: 4899,
    mrp: 6499,
    rating: 4.8,
    reviewsCount: 12,
    isNew: true,
    isTrending: false,
    isBestseller: true,
    isSale: true,
    stock: 6,
    images: ['https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Festive mustard yellow printed kurta & sharara matching duo.',
    fabric: 'Georgette & Cotton Silk',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },

  // 2. Sister & Sister Sets (3 products)
  {
    id: 'th-s201',
    name: 'Pastel Pink & Peach Sister & Sister Lehenga Combo',
    slug: 'pastel-pink-and-peach-sister-and-sister-lehenga-combo',
    category: 'Siblings',
    subcategory: 'Sister & Sister Sets',
    collectionName: 'Festive',
    brand: 'Little Royal',
    ageRange: '0-8',
    sizes: ['Combo 2Y & 4Y', 'Combo 4Y & 6Y'],
    colors: [{ name: 'Pink', hex: '#FF80AB' }],
    price: 4499,
    mrp: 5899,
    rating: 4.9,
    reviewsCount: 16,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: true,
    stock: 8,
    images: ['https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Twin pastel pink & peach matching lehenga choli combo for sisters.',
    fabric: 'Soft Silk & Net',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-s202',
    name: 'Mint Green Sister & Sister Sharara Set',
    slug: 'mint-green-sister-and-sister-sharara-set',
    category: 'Siblings',
    subcategory: 'Sister & Sister Sets',
    collectionName: 'Festive',
    brand: 'Festive Blooms',
    ageRange: '9-12',
    sizes: ['Combo 6Y & 8Y', 'Combo 8Y & 10Y'],
    colors: [{ name: 'Mint Green', hex: '#A5D6A7' }],
    price: 4699,
    mrp: 6199,
    rating: 4.8,
    reviewsCount: 11,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: false,
    stock: 9,
    images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Refreshing mint green matching sharara duo for sisters.',
    fabric: 'Chanderi Silk',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-s203',
    name: 'Lavender Net Sister & Sister Festive Set',
    slug: 'lavender-net-sister-and-sister-festive-set',
    category: 'Siblings',
    subcategory: 'Sister & Sister Sets',
    collectionName: 'Wedding',
    brand: 'Tohay Heritage',
    ageRange: '13-16',
    sizes: ['Combo 10Y & 12Y', 'Combo 12Y & 14Y'],
    colors: [{ name: 'Lavender', hex: '#CE93D8' }],
    price: 4999,
    mrp: 6599,
    rating: 4.9,
    reviewsCount: 15,
    isNew: true,
    isTrending: false,
    isBestseller: true,
    isSale: true,
    stock: 5,
    images: ['https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Regal lavender embroidered net festive gowns for sisters.',
    fabric: 'Embroidered Net',
    care: 'Dry Clean Only',
    occasion: 'Wedding',
    isActive: true
  },

  // 3. Brother & Brother Sets (3 products)
  {
    id: 'th-s301',
    name: 'Sky Blue & White Brother & Brother Kurta Set',
    slug: 'sky-blue-and-white-brother-and-brother-kurta-set',
    category: 'Siblings',
    subcategory: 'Brother & Brother Sets',
    collectionName: 'Festive',
    brand: 'Tohay Heritage',
    ageRange: '0-8',
    sizes: ['Combo 2Y & 4Y', 'Combo 4Y & 6Y'],
    colors: [{ name: 'Sky Blue', hex: '#38BDF8' }],
    price: 3999,
    mrp: 5299,
    rating: 4.8,
    reviewsCount: 14,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: true,
    stock: 10,
    images: ['https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Matching sky blue jacquard kurta pyjama duo for brothers.',
    fabric: 'Cotton Silk',
    care: 'Hand Wash',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-s302',
    name: 'Cream Jacquard Brother & Brother Nehru Jacket Set',
    slug: 'cream-jacquard-brother-and-brother-nehru-jacket-set',
    category: 'Siblings',
    subcategory: 'Brother & Brother Sets',
    collectionName: 'Festive',
    brand: 'Little Royal',
    ageRange: '9-12',
    sizes: ['Combo 6Y & 8Y', 'Combo 8Y & 10Y'],
    colors: [{ name: 'Yellow', hex: '#FDE047' }],
    price: 4599,
    mrp: 5999,
    rating: 4.9,
    reviewsCount: 13,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: false,
    stock: 8,
    images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Matching cream & gold Nehru jacket sets for brothers.',
    fabric: 'Jacquard Silk',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-s303',
    name: 'Royal Navy Silk Brother & Brother Sherwani Set',
    slug: 'royal-navy-silk-brother-and-brother-sherwani-set',
    category: 'Siblings',
    subcategory: 'Brother & Brother Sets',
    collectionName: 'Wedding',
    brand: 'Tohay Heritage',
    ageRange: '13-16',
    sizes: ['Combo 10Y & 12Y', 'Combo 12Y & 14Y'],
    colors: [{ name: 'Navy', hex: '#1E3A8A' }],
    price: 4999,
    mrp: 6699,
    rating: 5.0,
    reviewsCount: 9,
    isNew: true,
    isTrending: false,
    isBestseller: true,
    isSale: true,
    stock: 6,
    images: ['https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Regal navy blue embroidered sherwani twin combo for brothers.',
    fabric: 'Raw Silk',
    care: 'Dry Clean Only',
    occasion: 'Wedding',
    isActive: true
  },

  // 4. Unisex Sibling Sets (3 products)
  {
    id: 'th-s401',
    name: 'Heritage Yellow Unisex Sibling Festive Combo',
    slug: 'heritage-yellow-unisex-sibling-festive-combo',
    category: 'Siblings',
    subcategory: 'Unisex Sibling Sets',
    collectionName: 'Festive',
    brand: 'Festive Blooms',
    ageRange: '0-8',
    sizes: ['Combo 2Y & 4Y', 'Combo 4Y & 6Y'],
    colors: [{ name: 'Yellow', hex: '#FDE047' }],
    price: 3899,
    mrp: 4999,
    rating: 4.8,
    reviewsCount: 15,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: true,
    stock: 12,
    images: ['https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Unisex yellow Haldi special matching sibling ethnic wear set.',
    fabric: 'Pure Cotton Silk',
    care: 'Hand Wash',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-s402',
    name: 'Emerald Green Unisex Sibling Festive Combo',
    slug: 'emerald-green-unisex-sibling-festive-combo',
    category: 'Siblings',
    subcategory: 'Unisex Sibling Sets',
    collectionName: 'Festive',
    brand: 'Festive Blooms',
    ageRange: '9-12',
    sizes: ['Combo 6Y & 8Y', 'Combo 8Y & 10Y'],
    colors: [{ name: 'Mint Green', hex: '#A5D6A7' }],
    price: 4299,
    mrp: 5499,
    rating: 4.9,
    reviewsCount: 11,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isSale: false,
    stock: 9,
    images: ['https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Rich emerald green matching kurta-skirt sibling combo.',
    fabric: 'Chanderi Silk',
    care: 'Dry Clean Only',
    occasion: 'Festive',
    isActive: true
  },
  {
    id: 'th-s403',
    name: 'Royal Maroon Unisex Sibling Festive Combo',
    slug: 'royal-maroon-unisex-sibling-festive-combo',
    category: 'Siblings',
    subcategory: 'Unisex Sibling Sets',
    collectionName: 'Wedding',
    brand: 'Tohay Heritage',
    ageRange: '13-16',
    sizes: ['Combo 10Y & 12Y', 'Combo 12Y & 14Y'],
    colors: [{ name: 'Maroon', hex: '#880E4F' }],
    price: 4599,
    mrp: 5999,
    rating: 4.9,
    reviewsCount: 14,
    isNew: true,
    isTrending: false,
    isBestseller: true,
    isSale: true,
    stock: 7,
    images: ['https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=800&q=80'],
    shortDescription: 'Luxury royal maroon embroidered unisex sibling wedding ensemble.',
    fabric: 'Art Silk Dupion',
    care: 'Dry Clean Only',
    occasion: 'Wedding',
    isActive: true
  }
];

const seedCategories = [
  {
    id: 'cat-boys',
    name: 'Boys Collection',
    slug: 'boys',
    parentCategory: 'Main',
    image: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=600&q=80',
    description: 'Smart ethnic wear for boys',
    subcategories: [],
    productsCount: 0,
    status: 'Active',
    sortOrder: 1
  },
  {
    id: 'cat-girls',
    name: 'Girls Collection',
    slug: 'girls',
    parentCategory: 'Main',
    image: 'https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&w=600&q=80',
    description: 'Festive lehengas and gowns for girls',
    subcategories: [],
    productsCount: 0,
    status: 'Active',
    sortOrder: 2
  },
  {
    id: 'cat-siblings',
    name: 'Siblings Matching',
    slug: 'siblings',
    parentCategory: 'Main',
    image: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=600&q=80',
    description: 'Coordinated outfits for brothers & sisters',
    subcategories: [],
    productsCount: 0,
    status: 'Active',
    sortOrder: 3
  },
  {
    id: 'cat-age',
    name: 'Shop By Age',
    slug: 'shop-by-age',
    parentCategory: 'Main',
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=600&q=80',
    description: 'Explore outfits by age group',
    subcategories: [],
    productsCount: 0,
    status: 'Active',
    sortOrder: 4
  },
  {
    id: 'cat-new',
    name: 'New Arrivals',
    slug: 'new-arrivals',
    parentCategory: 'Main',
    image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=600&q=80',
    description: 'Fresh festive additions',
    subcategories: [],
    productsCount: 0,
    status: 'Active',
    sortOrder: 5
  },
  {
    id: 'cat-collections',
    name: 'Collections',
    slug: 'collections',
    parentCategory: 'Main',
    image: 'https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&w=600&q=80',
    description: 'Festive & Wedding Special Edits',
    subcategories: [],
    productsCount: 0,
    status: 'Active',
    sortOrder: 6
  },
  {
    id: 'cat-sale',
    name: 'Sale',
    slug: 'sale',
    parentCategory: 'Main',
    image: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=600&q=80',
    description: 'Exclusive discounts & festive deals',
    subcategories: [],
    productsCount: 0,
    status: 'Active',
    sortOrder: 7
  }
];

const seedBrands = [
  { id: 'br-1', code: 'br-1', name: 'Tohay Heritage', logo: 'https://via.placeholder.com/150', isActive: true },
  { id: 'br-2', code: 'br-2', name: 'Little Royal', logo: 'https://via.placeholder.com/150', isActive: true },
  { id: 'br-3', code: 'br-3', name: 'Festive Blooms', logo: 'https://via.placeholder.com/150', isActive: true },
];

const seedCoupons: any[] = [];

const seedBanners = [
  {
    id: 'ban-hero-1',
    title: 'Royal Indian Festive',
    highlightTitle: 'Collection 2026',
    subtitle: 'Handcrafted ethnic wear made for every little celebration.',
    btnPrimaryText: 'BOYS',
    btnPrimaryLink: '/boys',
    btnSecondaryText: 'GIRLS',
    btnSecondaryLink: '/girls',
    image: '/uploads/hero-slider-1.png',
    imageUrl: '/uploads/hero-slider-1.png',
    placement: 'Homepage Main Hero Carousel',
    position: 'Hero Slider',
    status: 'Active',
    sortOrder: 1,
  },
  {
    id: 'ban-hero-2',
    title: 'Celebration & Wedding',
    highlightTitle: 'Festive Sparkle',
    subtitle: 'Royal kurtas, lehengas & twinning sibling outfits.',
    btnPrimaryText: 'BOYS',
    btnPrimaryLink: '/boys',
    btnSecondaryText: 'GIRLS',
    btnSecondaryLink: '/girls',
    image: '/uploads/hero-slider-2.png',
    imageUrl: '/uploads/hero-slider-2.png',
    placement: 'Homepage Main Hero Carousel',
    position: 'Hero Slider',
    status: 'Active',
    sortOrder: 2,
  },
  {
    id: 'ban-hero-3',
    title: 'Little Prince & Princess',
    highlightTitle: 'New Arrivals',
    subtitle: 'Premium silk, organza & velvet ensembles crafted with love.',
    btnPrimaryText: 'BOYS',
    btnPrimaryLink: '/boys',
    btnSecondaryText: 'GIRLS',
    btnSecondaryLink: '/girls',
    image: '/uploads/hero-slider-3.png',
    imageUrl: '/uploads/hero-slider-3.png',
    placement: 'Homepage Main Hero Carousel',
    position: 'Hero Slider',
    status: 'Active',
    sortOrder: 3,
  },
  {
    id: 'ban-1',
    title: 'Celebrate Little Moments in Style',
    subtitle: 'Handcrafted Kids Festive Wear 2026',
    btnPrimaryText: 'SHOP GIRLS',
    btnPrimaryLink: '/girls',
    btnSecondaryText: 'SHOP BOYS',
    btnSecondaryLink: '/boys',
    image: 'https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&w=1200&q=80',
    link: '/collections',
    placement: 'Homepage Hero Banner',
    status: 'Active',
  },
  {
    id: 'ban-2',
    title: 'The Celebration Edit',
    subtitle: 'Handpicked ethnic styles designed for weddings & special moments.',
    btnPrimaryText: 'SHOP COLLECTION',
    btnPrimaryLink: '/collections',
    image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80',
    link: '/collections',
    placement: 'Homepage Celebration Edit',
    status: 'Active',
  },
  {
    id: 'ban-3',
    title: 'A Little Extra for Their Big Day',
    subtitle: 'Special Collection',
    btnSecondaryText: '',
    description: '05:12:34',
    link: '/sale',
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
    placement: 'Homepage Prepaid Offer',
    status: 'Active',
  }
];

async function bootstrap() {
  console.log('🌱 Starting MongoDB database seeding for Tohay Kids...');
  const app = await NestFactory.createApplicationContext(AppModule);

  const userModel = app.get<Model<UserDocument>>(getModelToken(User.name));
  const productModel = app.get<Model<ProductDocument>>(getModelToken(Product.name));
  const categoryModel = app.get<Model<CategoryDocument>>(getModelToken(Category.name));
  const brandModel = app.get<Model<BrandDocument>>(getModelToken(Brand.name));
  const couponModel = app.get<Model<CouponDocument>>(getModelToken(Coupon.name));
  const bannerModel = app.get<Model<BannerDocument>>(getModelToken(Banner.name));
  const settingsModel = app.get<Model<StoreSettingsDocument>>(getModelToken(StoreSettings.name));

  // 1. Seed Admin User
  const adminEmail = 'admin@tohaykids.com';
  let admin = await userModel.findOne({ email: adminEmail }).exec();
  if (!admin) {
    const passwordHash = await bcrypt.hash('AdminPassword123!', 10);
    admin = new userModel({
      name: 'Super Admin',
      email: adminEmail,
      passwordHash: passwordHash,
      role: Role.ADMIN,
      phone: '+91 98765 43210',
      isEmailVerified: true,
    });
    await admin.save();
    console.log(`✅ Admin account created: ${adminEmail}`);
  }

  // 2. Seed Sample Customer User
  const customerEmail = 'ananya.sharma@gmail.com';
  let customer = await userModel.findOne({ email: customerEmail }).exec();
  if (!customer) {
    const passwordHash = await bcrypt.hash('Customer123!', 10);
    customer = new userModel({
      name: 'Ananya Sharma',
      email: customerEmail,
      passwordHash: passwordHash,
      role: Role.CUSTOMER,
      phone: '+91 98765 43210',
      isEmailVerified: true,
      memberTier: 'Gold Member',
      coins: 450,
      referralCode: 'TOHAY-ANANYA-2026',
      kids: [
        { name: 'Anaya', age: '5 Years', preferredSize: '5-6Y', gender: 'Girl' },
        { name: 'Aarav', age: '8 Years', preferredSize: '7-8Y', gender: 'Boy' },
      ],
    });
    await customer.save();
    console.log(`✅ Customer account created: ${customerEmail}`);
  }

  // 3. Clear products (so products only exist when added via Admin)
  await productModel.deleteMany({}).exec();
  console.log('✅ Cleared all sample products from MongoDB.');

  // 4. Seed Categories with empty subcategories array
  for (const c of seedCategories) {
    await categoryModel.findOneAndUpdate(
      { $or: [{ id: c.id }, { slug: c.slug }] },
      c,
      { upsert: true, new: true }
    ).exec();
  }
  console.log(`✅ Seeded ${seedCategories.length} main categories (with empty subcategories array)`);

  // 5. Seed Brands
  for (const b of seedBrands) {
    await brandModel.findOneAndUpdate({ id: b.id }, b, { upsert: true }).exec();
  }
  console.log(`✅ Seeded ${seedBrands.length} brands`);

  // 6. Seed Coupons
  for (const cp of seedCoupons) {
    await couponModel.findOneAndUpdate({ code: cp.code }, cp, { upsert: true }).exec();
  }
  console.log(`✅ Seeded ${seedCoupons.length} coupons`);

  // 7. Seed Banners
  for (const bn of seedBanners) {
    await bannerModel.findOneAndUpdate({ id: bn.id }, bn, { upsert: true }).exec();
  }
  console.log(`✅ Seeded ${seedBanners.length} promotional banners`);

  // 8. Seed Store Settings
  const existingSettings = await settingsModel.findOne().exec();
  if (!existingSettings) {
    const settings = new settingsModel({
      storeName: 'Tohay Kids Festive Wear',
      contactEmail: 'admin@tohaykids.com',
      supportPhone: '+91 98765 43210',
      currencySymbol: '₹',
      currencyCode: 'INR',
      freeShippingThreshold: 1499,
      standardShippingFee: 99,
      gstTaxRate: 5,
    });
    await settings.save();
    console.log('✅ Store settings initialized');
  }

  console.log('🎉 MongoDB Database seeding completed successfully!');
  await app.close();
}

bootstrap().catch((err) => {
  console.error('❌ Seeding error:', err);
  process.exit(1);
});
